/*
    Part A - Project & Structure

    .csproj:
    This file contains project configuration, framework details, target .NET version,
    and build settings for the C# project.

    Program.cs:
    The main source file where application execution begins using C# Top-Level Statements.

    obj/:
    Contains temporary intermediate build files and compiled assets generated by .NET during compilation.

    bin/:
    Contains the final output files, including compiled binary executables (.exe) and DLL files.

    File-scoped namespace:
    Reduces code nesting and removes one level of indentation by eliminating 
    outer curly braces around the entire file content.

    Solution format:
    Uses standard .sln format to organize and manage one or more related projects.
*/


// Part B — Variables, Types & Casting

Console.WriteLine("Part B — Variables, Types & Casting");
RunPartB();
void RunPartB()
{
    // → Declaring variables of different types
    int age = 25;
    long population = 7800000000L;
    double temp = 36.6;
    decimal price = 19.99m;
    bool isStudent = true;
    char grade = 'A';
    string name = "John";
    var height = 5.9;

    Console.WriteLine(age);
    Console.WriteLine(age.GetType());

    Console.WriteLine(population);
    Console.WriteLine(population.GetType());

    Console.WriteLine(temp);
    Console.WriteLine(temp.GetType());

    Console.WriteLine(price);
    Console.WriteLine(price.GetType());

    Console.WriteLine(isStudent);
    Console.WriteLine(isStudent.GetType());

    Console.WriteLine(grade);
    Console.WriteLine(grade.GetType());

    Console.WriteLine(name);
    Console.WriteLine(name.GetType());

    Console.WriteLine(height);
    Console.WriteLine(height.GetType());

    // → Boxing and Unboxing
    int number = 42;
    object boxednum = number; // Boxing

    int unboxednum = (int)boxednum; // Unboxing

    // → Implicit and Explicit Casting

    int nnum = 160;
    long numm = nnum; // no needed to cast explicitly because long has a larger range than int
    Console.WriteLine(nnum + " " + numm);

    char ch = 'A';
    int z = ch; // no needed to cast because ch 'A' automatically converts to its ASCII value
    Console.WriteLine(ch + " " + z);

    double d = 9.56;
    int explicitCast = (int)d;
    int explicitCas2 = Convert.ToInt32(d);
    Console.WriteLine(d + " " + explicitCast + " " + explicitCas2);
    /*if we use cast ToInt → int truncates the decimal part(بيقطع اي جزء عشري ايا كان قيمته) ,
    when we used ToInt23 → it rounds the number to the nearest integer (بيقرب لاقرب رقم صحيح)*/

    // → Parsing

    string toparse = "123";
    int parsednum = int.Parse(toparse);
    Console.WriteLine(toparse + " -> " + parsednum);

    string toparse2 = "abbc";
    bool isParsed = int.TryParse(toparse2, out int result);
    if (!isParsed)
    {
        Console.WriteLine("Failed to parse the string.");
    }
    else
    {
        Console.WriteLine("Successfully parsed the string. → " + result);
    }

    // → Integer division trap

    int trap = 5 / 2; // Integer division, because both of numbers are integers
    Console.WriteLine("Integer result: " + trap);

    double trapDec = 5.0 / 2; // Decimal division, because one of the numbers is a double (5.0 is a double literal)
    Console.WriteLine("Decimal result: " + trapDec);

    // → float → decimal conversion
    float myFloat = 5.75f;

    // decimal implicitDecimal = myFloat; 
    // Compilation Error: Compiler refuses implicit conversion due to different internal representation

    decimal explicitDecimal = (decimal)myFloat; // Explicit cast required
    Console.WriteLine("Float to Decimal: " + explicitDecimal);
}

Console.WriteLine("Break");

// Part C — Value vs. Reference Types

Console.WriteLine("Part C — Value vs. Reference Types");
RunPartC();

void RunPartC()
{
    Console.WriteLine("--- Experiment 1: Struct (Value Type) ---");

    Point p1 = new Point { X = 1, Y = 2 };
    Point p2 = p1; // Creates a completely independent copy on the stack

    p2.X = 99; // Modifying p2 does NOT affect p1

    Console.WriteLine("p1.X: " + p1.X);
    Console.WriteLine("p2.X: " + p2.X);
    // Explanation: Point is a struct (Value Type) stored directly on the stack.
    // Assigning p2 = p1 performs a full byte-by-byte copy of the data, so p1 and p2 are independent.


    // Experiment 2 — class reference semantics (Reference Type)
    Console.WriteLine("\n--- Experiment 2: Class (Reference Type) ---");

    Order o1 = new Order
    {
        OrderId = 101,
        CustomerName = "Alice",
        Quantity = 3,
        UnitPrice = 50.0m,
        TotalPrice = 0m,
        IsPaid = false,
        DiscountPercent = 10.0,
        ShippingCity = "Cairo",
        Priority = 'H',
        ItemCode = 9876543210L
    };

    o1.CalculateTotal();

    Order o2 = o1; // Copies the reference (address), not the object itself

    o2.IsPaid = true; // Modifying through o2 affects the same object in the heap

    Console.WriteLine("o1.IsPaid: " + o1.IsPaid);
    Console.WriteLine("o2.IsPaid: " + o2.IsPaid);
    // Explanation: Order is a class (Reference Type) stored on the heap.
    // Assigning o2 = o1 copies only the reference pointer, meaning both variables point to the exact same memory address (shared heap identity).

    object boxedOrder = o1; // No boxing occurs here; Order is already a reference type, so it just stores the reference address.
    Order o3 = (Order)boxedOrder;

    Console.WriteLine("Are o1 and o3 the same instance? " + object.ReferenceEquals(o1, o3));

    // Calling PrintSummary() to verify reflection of change made through o2
    o2.PrintSummary();


    Console.WriteLine("\n--- Explanation Summary ---");
    Console.WriteLine("1. Value types live directly on the Stack (or inline inside heap objects), while reference types have their actual data on the Heap with a pointer stored on the Stack.");
    Console.WriteLine("2. For value types, assignment (=) copies the actual underlying data/value, creating two independent copies.");
    Console.WriteLine("3. For reference types, assignment (=) copies only the memory reference (memory address), so both variables point to the exact same object in heap memory.");
    Console.WriteLine("4. Storing a reference type inside an object variable does not create a new object or trigger boxing; it simply stores the existing object's reference inside a variable of type object.");
}

Console.WriteLine("Break");

// Part D — Scope & Operators

Console.WriteLine("Part D — Scope & Operators");
RunPartD();

void RunPartD()
{
    Console.WriteLine("--- D1: Scope ---");
    ScopeDemo.Method1();
    ScopeDemo.Method2();

    MethodWithLocalScope();
    // Console.WriteLine(methodScopedVar); 
    // Error: methodScopedVar is only accessible inside MethodWithLocalScope (Method Scope)

    for (int i = 0; i < 3; i++)
    {
        int insideLoop = i * 10;
        Console.WriteLine($"Loop index: {i}, inside value: {insideLoop}");
    }
    // Console.WriteLine(i);
    // Console.WriteLine(insideLoop);
    // Error: Variables destroyed after loop ends (Block Scope)


    Console.WriteLine("\n--- D2: Compound Assignment Operators ---");
    int total = 100;
    Console.WriteLine("Initial total: " + total);

    total += 20;
    Console.WriteLine("After += 20: " + total);

    total -= 10;
    Console.WriteLine("After -= 10: " + total);

    total *= 2;
    Console.WriteLine("After *= 2: " + total);

    total /= 4;
    Console.WriteLine("After /= 4: " + total);

    total %= 7;
    Console.WriteLine("After %= 7: " + total);


    Console.WriteLine("\n--- D3: Bitwise Operators ---");
    int a = 12;
    int b = 10;

    Console.WriteLine("a & b: " + (a & b));

    Console.WriteLine("a | b: " + (a | b));

    Console.WriteLine("a ^ b: " + (a ^ b));

    // Difference between & and &&:
    // && stops evaluation if the left operand is false (short-circuit), while & always evaluates both sides.
}

void MethodWithLocalScope()
{
    string methodScopedVar = "Local";
    Console.WriteLine("Inside method: " + methodScopedVar);
}

Console.WriteLine("Break");


// Types declarations at the very bottom
public struct Point
{
    public int X;
    public int Y;
}

public class ScopeDemo
{
    private static int myField = 500;

    public static void Method1()
    {
        Console.WriteLine("Read from Method 1 (Field Scope): " + myField);
    }

    public static void Method2()
    {
        Console.WriteLine("Read from Method 2 (Field Scope): " + myField);
    }
}